# Generated by Django 3.0.6 on 2020-06-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolls',
            old_name='time',
            new_name='timeStamp',
        ),
    ]
