# Generated by Django 3.0.6 on 2020-06-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_auto_20200621_2213'),
        ('rolls', '0004_rolls_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolls',
            name='ep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='episodes.Episode'),
        ),
    ]
