# Generated by Django 3.0.6 on 2020-06-22 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_auto_20200621_2213'),
        ('rolls', '0006_auto_20200621_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolls',
            name='ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='episodes.Episode'),
        ),
    ]
