# Generated by Django 3.0.6 on 2020-06-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0008_auto_20200622_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolls',
            old_name='timeStamp',
            new_name='time_stamp',
        ),
    ]
