# Generated by Django 3.0.6 on 2020-07-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0013_die'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disregarded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantages_disregarded', to='rolls.Rolls')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='rolls.AdvantageType')),
                ('used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantages_used', to='rolls.Rolls')),
            ],
        ),
    ]
