# Generated by Django 3.1.4 on 2020-12-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0017_kill_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolls',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
