# Generated by Django 3.0.6 on 2020-07-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0010_levelprog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='episodes.Episode')),
            ],
        ),
    ]
