# Generated by Django 3.0.6 on 2020-08-02 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0022_statsheet_level'),
        ('rolls', '0017_kill_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=-1)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_taken', to='characters.Character')),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='damages.DamageType')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='rolls.Rolls')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_dealt', to='characters.Character')),
            ],
        ),
    ]
