# Generated by Django 3.0.6 on 2020-06-23 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('characters', '0002_auto_20200623_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtaken',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
