# Generated by Django 3.0.6 on 2020-06-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20200623_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtaken',
            old_name='character_id',
            new_name='character',
        ),
    ]
