# Generated by Django 3.0.6 on 2020-06-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20200623_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Allignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_health', models.IntegerField(default=0)),
                ('armour_class', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=30)),
                ('initiative_bonus', models.IntegerField(default=0)),
                ('proficiency_bonus', models.IntegerField(default=0)),
                ('hit_die', models.CharField(max_length=50)),
                ('inspiration_die', models.IntegerField(default=0)),
                ('equipment', models.TextField(blank=True)),
                ('features_traits', models.TextField(blank=True)),
                ('weapons', models.TextField(blank=True)),
                ('casting_class', models.TextField(blank=True)),
                ('spell_attack_bonus', models.IntegerField(default=0)),
                ('cantrips', models.IntegerField(default=0)),
                ('slots_one', models.IntegerField(default=0)),
                ('slots_two', models.IntegerField(default=0)),
                ('slots_three', models.IntegerField(default=0)),
                ('slots_four', models.IntegerField(default=0)),
                ('slots_five', models.IntegerField(default=0)),
                ('slots_six', models.IntegerField(default=0)),
                ('slots_seven', models.IntegerField(default=0)),
                ('slots_eight', models.IntegerField(default=0)),
                ('slots_nine', models.IntegerField(default=0)),
                ('allignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_sheets', to='characters.Allignment')),
                ('casting_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Ability')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_sheets', to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.IntegerField(default=0)),
                ('profcient', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Skill')),
                ('stat_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.StatSheet')),
            ],
        ),
        migrations.CreateModel(
            name='SavingThrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='characters.Ability')),
                ('stat_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_throws', to='characters.StatSheet')),
            ],
        ),
        migrations.CreateModel(
            name='OtherNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_spells', to='characters.StatSheet')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_by', to='characters.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_by', to='characters.Language')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='characters.StatSheet')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=10)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='characters.Ability')),
                ('stat_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_scores', to='characters.StatSheet')),
            ],
        ),
    ]
