# Generated by Django 3.0.6 on 2020-06-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20200630_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtaken',
            name='character',
        ),
        migrations.AddField(
            model_name='classtaken',
            name='stat_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='characters.StatSheet'),
        ),
    ]
