# Generated by Django 3.0.6 on 2020-06-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20200630_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsheet',
            name='casting_ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Ability'),
        ),
    ]
