# Generated by Django 3.0.6 on 2020-07-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0017_auto_20200702_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spell',
            new_name='Spells',
        ),
        migrations.RenameField(
            model_name='learnedspell',
            old_name='spell',
            new_name='spell_old',
        ),
    ]
