# Generated by Django 3.0.6 on 2020-07-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_auto_20200702_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnedlanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='learnedlanguage',
            name='sheet',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='LearnedLanguage',
        ),
    ]
