# Generated by Django 3.0.6 on 2020-06-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_ability_abilityscore_allignment_language_learnedlanguage_learnedspell_othernames_savingthrow_skill_s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allignment',
            new_name='Alignment',
        ),
        migrations.RenameField(
            model_name='statsheet',
            old_name='allignment',
            new_name='alignment',
        ),
    ]
