# Generated by Django 3.0.6 on 2020-06-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20200630_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsheet',
            name='alignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_sheets', to='characters.Alignment'),
        ),
    ]
