# Generated by Django 3.0.6 on 2020-07-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20200630_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingthrow',
            old_name='profcient',
            new_name='proficient',
        ),
        migrations.RenameField(
            model_name='skilllist',
            old_name='profcient',
            new_name='proficient',
        ),
    ]
