# Generated by Django 3.0.6 on 2020-07-02 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('characters', '0014_auto_20200702_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='character',
            name='char_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='characters.CharacterType'),
        ),
        migrations.AlterField(
            model_name='classtaken',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='classes.Class'),
        ),
    ]
