# Generated by Django 3.0.6 on 2020-07-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('characters', '0015_auto_20200702_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='players.Player'),
        ),
    ]
