# Generated by Django 3.0.6 on 2020-07-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_auto_20200702_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnedSpells',
        ),
        migrations.DeleteModel(
            name='Spells',
        ),
    ]
