# Generated by Django 3.0.6 on 2020-07-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_auto_20200703_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsheet',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
