# Generated by Django 3.0.6 on 2020-07-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0010_levelprog'),
        ('characters', '0017_auto_20200702_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField(blank=True, default=0)),
                ('cantrip', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpellCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_level', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='characters.Character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='episodes.Episode')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='spells.Spell')),
            ],
        ),
    ]
