# Generated by Django 3.0.6 on 2020-07-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_learnedspell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellcast',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
