# Generated by Django 3.0.6 on 2020-07-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_spellcast_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellcast',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
