# Generated by Django 3.1.4 on 2020-12-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_spellcast_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spellcast',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
