# Generated by Django 3.1.4 on 2020-12-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0005_auto_20201221_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spellcast',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
