# Generated by Django 3.0.6 on 2020-07-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_statsheet_level'),
        ('rolls', '0013_die'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='characters.Character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatievs', to='encounters.CombatEncounter')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.Rolls')),
            ],
        ),
        migrations.CreateModel(
            name='CombatApperance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='characters.Character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apperances', to='encounters.CombatEncounter')),
            ],
        ),
    ]
