# Generated by Django 3.0.6 on 2020-06-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_auto_20200621_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='airDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
