# Generated by Django 3.0.6 on 2020-06-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('episodes', '0004_auto_20200622_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='campaigns.Campaign'),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
