# Generated by Django 3.0.6 on 2020-06-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20200623_0109'),
        ('episodes', '0007_auto_20200624_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApperanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apperance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apperances', to='episodes.ApperanceType')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apperances', to='characters.Character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apperances', to='episodes.Episode')),
            ],
        ),
    ]
