# Generated by Django 3.0.6 on 2020-06-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0008_apperance_apperancetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apperance',
            old_name='appearance_type',
            new_name='apperance_type',
        ),
    ]
