# Generated by Django 3.0.6 on 2020-07-16 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('episodes', '0011_auto_20200716_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='apperance',
            name='player',
        ),
        migrations.AlterField(
            model_name='live',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_episodes', to='episodes.Episode'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='episodes.AttendanceType')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='episodes.Episode')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='players.Player')),
            ],
        ),
    ]
