# Generated by Django 3.0.6 on 2020-06-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RollType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('naturalValue', models.IntegerField(default=0)),
                ('finalValue', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=200)),
                ('rollType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.RollType')),
            ],
        ),
    ]
