# Generated by Django 3.0.6 on 2020-06-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0010_rolls_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolls',
            name='roll_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='rolls.RollType'),
        ),
    ]
