# Generated by Django 3.0.6 on 2020-07-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0011_auto_20200623_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolls',
            name='damage',
            field=models.TextField(blank=True),
        ),
    ]
