# Generated by Django 3.0.6 on 2020-07-18 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_statsheet_level'),
        ('rolls', '0014_advantage_advantagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolls',
            name='kill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='characters.Character')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='rolls.Rolls')),
            ],
        ),
    ]
