# Generated by Django 3.0.6 on 2020-07-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0015_auto_20200718_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolls',
            name='final_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rolls',
            name='natural_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
