# Generated by Django 3.0.6 on 2020-07-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0016_auto_20200702_0511'),
        ('episodes', '0010_levelprog'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PotionUseage',
            new_name='PotionUsage',
        ),
    ]
