# Generated by Django 3.0.6 on 2020-07-05 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0013_die'),
        ('characters', '0021_auto_20200703_0007'),
        ('items', '0002_auto_20200702_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('attack_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponeOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons_owned', to='characters.StatSheet')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='items.Weapon')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_num', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='items.DamageType')),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.Die')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_die', to='items.Weapon')),
            ],
        ),
    ]
