# Generated by Django 3.0.6 on 2020-07-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0013_die'),
        ('items', '0003_damagetype_weapon_weapondamage_weaponeowned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapondamage',
            old_name='bonus',
            new_name='modifier',
        ),
        migrations.AlterField(
            model_name='weapondamage',
            name='damage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='items.DamageType'),
        ),
        migrations.AlterField(
            model_name='weapondamage',
            name='die',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rolls.Die'),
        ),
    ]
