# Generated by Django 3.0.6 on 2020-06-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.TextField()),
                ('airDate', models.DateField()),
                ('description', models.TextField()),
                ('length', models.IntegerField(default=0)),
                ('gameStart', models.IntegerField(default=0)),
                ('breakStart', models.IntegerField(default=0)),
                ('breakEnd', models.IntegerField(default=0)),
                ('gameEnd', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episodes.Campaign')),
            ],
        ),
    ]
