# Generated by Django 3.0.6 on 2020-07-01 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20200630_0518'),
        ('episodes', '0009_auto_20200628_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_ups', to='episodes.Episode')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_ups', to='characters.StatSheet')),
            ],
        ),
    ]
