# Generated by Django 3.0.8 on 2020-08-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0013_vodlinks_vodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateField(),
        ),
    ]
