# Generated by Django 3.0.6 on 2020-07-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0019_auto_20200702_2317'),
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_spells', to='characters.StatSheet')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_by', to='spells.Spell')),
            ],
        ),
    ]
