# Generated by Django 3.0.6 on 2020-07-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200705_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapondamage',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='items.Weapon'),
        ),
    ]
