# Generated by Django 3.0.6 on 2020-07-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0013_die'),
        ('items', '0005_auto_20200707_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rolls.Rolls')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='items.Weapon')),
            ],
        ),
    ]
